### ISSUE TITLE
--sqlFile not working with PostgreSQL databases

### ISSUE THREAD

**Issue by fjgal** [spotify/dbeam#122]
When using the command line option `--sqlFile` the generated query is not compatible with PostgreSQL.

It fails with:

```
ERROR: subquery in FROM must have an alias
  Hint: For example, FROM (SELECT ...) [AS] foo.
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.spotify.dbeam.avro.JdbcAvroSchema.createSchemaByReadingOneRow(JdbcAvroSchema.java:83)
	at com.spotify.dbeam.avro.BeamJdbcAvroSchema.createSchema(BeamJdbcAvroSchema.java:55)
	at com.spotify.dbeam.jobs.JdbcAvroJob.prepareExport(JdbcAvroJob.java:101)
	at com.spotify.dbeam.jobs.JdbcAvroJob.runExport(JdbcAvroJob.java:145)
	at com.spotify.
```

The problem is that the template used by the query builder is not setting an alias for the subquery:

```java
    public String getBaseSql() {
      return String.format("%s FROM (%s) %s",
              selectClause, userSqlQuery, DEFAULT_WHERE_CLAUSE);
    }
```

instead it should be something like:

```java
    public String getBaseSql() {
      return String.format("%s FROM (%s) as user_sql_query %s",
              selectClause, userSqlQuery, DEFAULT_WHERE_CLAUSE);
    }
```

I'll submit a PR.

BTW, great project!

**Comment by ra1861** [comment]
[Good read](https://stackoverflow.com/questions/14767209/subquery-in-from-must-have-an-alias) about this.
