### ISSUE TITLE
NoClassDefFoundError: com/google/api/client/json/gson/GsonFactory

### ISSUE THREAD

**Issue by adamlawrencium** [spotify/dbeam#340]
Hi there! Forgive me if this is a simple issue, but I'm not familiar with Java/JVM. I built the library and run it how you described here: https://github.com/spotify/dbeam#usage-examples.

dbeam managed to create the Avro schema, but failed at the next step. It looks like we're missing a class or library? Would you know how to add it to the project, perhaps via an additional command line argument or installing via maven?

Thanks!

```
[main] INFO com.spotify.dbeam.avro.BeamJdbcAvroSchema - Elapsed time to schema 0.208 seconds
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/client/json/gson/GsonFactory
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:92)
        at org.apache.beam.sdk.extensions.gcp.auth.GcpCredentialFactory.getCredential(GcpCredentialFactory.java:63)
        at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpUserCredentialsFactory.create(GcpOptions.java:268)
        at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpUserCredentialsFactory.create(GcpOptions.java:257)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:605)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:546)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:171)
        at com.sun.proxy.$Proxy22.getGcpCredential(Unknown Source)
        at org.apache.beam.sdk.extensions.gcp.util.Transport.newStorageClient(Transport.java:98)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:104)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:93)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:605)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:546)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:171)
        at com.sun.proxy.$Proxy22.getGcsUtil(Unknown Source)
        at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:135)
        at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.create(GcsFileSystem.java:61)
        at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:244)
        at org.apache.beam.sdk.io.FileSystems.create(FileSystems.java:231)
        at com.spotify.dbeam.beam.BeamHelper.writeToFile(BeamHelper.java:80)
        at com.spotify.dbeam.beam.BeamHelper.saveStringOnSubPath(BeamHelper.java:88)
        at com.spotify.dbeam.jobs.JdbcAvroJob.prepareExport(JdbcAvroJob.java:119)
        at com.spotify.dbeam.jobs.JdbcAvroJob.runExport(JdbcAvroJob.java:164)
        at com.spotify.dbeam.jobs.JdbcAvroJob.main(JdbcAvroJob.java:175)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.json.gson.GsonFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 24 more
```

**Comment by labianchin** [comment]
It looks like last bump of Beam SDK left out a few dependencies. 7612a7730fd976b3e031dad9b563bbab89180be5 likely solves it: I ran `./dbeam-core/target/dbeam-core-shaded.jar` before and after and it works well after that change.

Can you try again with latest changes.

**Comment by labianchin** [comment]
Closing the issue for now. Feel free to reopen if the problem persists in newer versions.
